.gitignore, .vscode/extensions.json, .vscode/settings.json, src/backend/README.md, src/backend/main.py, src/backend/request_testing.http, src/backend/requirements.txt
- created src/backend folder
- initialized fastapi app with a couple example requests
- added requirements.txt for package management
- added README.md with installation instructions
- included black for Python formatting
- included REST client for testing API requests
- added .vscode folder to prompt devs to install extensions when they open the repo and to enable the formatter
- added .gitignore for ignore venv files
=> [MEE-41] feat: create backend

src/backend/README.md
Updated the backend README with improved documentation and instructions. Part of MEE-43 and MEE-44.
- Included a Testing section with instructions for pytest and manual testing
- Added a Documentation section with links to API docs
- Added an "Adding Packages" section with instructions for updating requirements.txt
- Updated the "Getting Started" instructions for running the server
1. Review the updated README.md file in the backend directory
2. Follow the new instructions to run the server and access the API documentation
3. Try running the test suite using pytest as described in the Testing section
4. Attempt to add a new package following the instructions in the "Adding Packages" section
This update improves the developer experience by providing more comprehensive documentation and …
=> docs: update backend README with testing instructions

.gitignore
=> fix: hide node_modules and *.webm files from bot src folders

src/bots/meets/package.json, src/bots/meets/pnpm-lock.yaml, src/bots/meets/src/index.ts
Meeting bot that can join meets.
Completes MEE-63
=> feat: bot joins google meet 

src/bots/meets/src/index.ts
=> meets-leave-on-empty-meeting

src/bots/teams/src/index.ts
=> feat: make sure the bot mutes it's own microphone before joining

src/bots/teams/src/index.ts
=> feat: leave when the meeting ends

src/frontend/.env.example, src/frontend/drizzle/0001_typical_logan.sql, src/frontend/drizzle/meta/0001_snapshot.json, src/frontend/drizzle/meta/_journal.json, src/frontend/src/env.js, src/frontend/src/server/auth/config.ts, src/frontend/src/server/db/schema.ts
complete MEE-79
collaborator @err53
=> refactor: replace discord with github auth

src/frontend/components.json, src/frontend/package.json, src/frontend/pnpm-lock.yaml, src/frontend/src/lib/utils.ts, src/frontend/src/styles/globals.css, src/frontend/tailwind.config.ts
=> task: add shadcn

src/bots/teams/src/index.ts
=> fix: add missing imports and dotenv config

src/bots/zoom/Dockerfile, src/bots/zoom/package.json, src/bots/zoom/pnpm-lock.yaml, src/bots/zoom/src/index.ts
=> feat: bot uploads to s3

src/bots/teams/src/index.ts
=> feat: Call a dummy callback url once the upload is complete

src/bots/teams/src/index.ts
=> feat: Make the Bot Wait in the Waiting Room

src/backend/app/models.py
=> refactor: store s3 object id rather than urls since urls are are temporary

src/backend/app/routes/bots.py, src/backend/pyproject.toml, src/backend/requirements-dev.lock, src/backend/requirements.lock
=> feat: return audio url when get bot

README.md
=> task: add roadmap onto README

README.md
=> task: add real-time video audio transcription to roadmap on README

.gitignore
=> chore: add the config file to the gitignore

src/bots/teams/Dockerfile, src/bots/teams/src/index.ts
=> feat: integrated config.json file with teams bot

src/bots/example-files/config-example.json, src/bots/teams/src/index.ts
=> feat: pulled callback url from config file

src/bots/teams/src/index.ts
=> feat: print statement at heartbeat interval

src/backend/src/db/schema.ts
Added TypeScript type definition for BotConfig using Zod schema inference
This way bot scripts can import it.
=> feat: add BotConfig type export

src/bots/zoom/package.json, src/bots/zoom/pnpm-lock.yaml, src/bots/zoom/src/index.ts, src/bots/zoom/src/trpc.ts
Added tRPC client integration to Zoom bot for type-safety with the backend.
For now I added an example heartbeat request as a demonstration, but commented it out.
Completes MEE-132
=> feat: integrate tRPC client in Zoom bot

src/bots/zoom/src/index.ts
=> feat: printing at heartbeat interval

src/backend/src/db/schema.ts, src/bots/example-files/config-example.json
towards MEE-141
towards MEE-149
=> feat: add automatic leave options to example config

src/bots/teams/package.json, src/bots/teams/pnpm-lock.yaml, src/bots/teams/src/index.ts, src/bots/teams/src/trpc.ts
Added tRPC client integration to Teams bot for type-safety with the backend.
For now I added an example heartbeat request as a demonstration, but commented it out.
@sarahsimionescu @sahibkhokhar @alexeckardt let me know if you have any thoughts!
https://github.com/user-attachments/assets/4e7605b1-c988-45a4-8568-a7639abbd546
Completes MEE-131
=> feat: integrate tRPC client in Teams bot

src/bots/teams/src/index.ts
complete MEE-141
complete MEE-149
=> feat: support waiting room timeout

src/bots/meets/Dockerfile, src/bots/meets/package.json, src/bots/meets/pnpm-lock.yaml, src/bots/meets/src/bot.ts, src/bots/meets/src/index.ts
=> feat: meets-upload-s3

src/bots/meets/Dockerfile, src/bots/meets/src/bot.ts, src/bots/meets/src/index.ts
=> feat:config-file-meet

src/bots/meets/src/bot.ts, src/bots/meets/src/index.ts
Completes MEE-138
Added heartbeat functionality to the Google Meet bot and refactored meeting URL configuration.
- Moved meeting URL configuration logic into the bot class
- Added state tracking properties to the MeetingBot class
- Implemented a heartbeat system that periodically reports bot status
- Created a heartbeat loop that runs alongside the main bot process
- Modified bot constructor to accept only botSettings parameter
1. Initialize a new MeetingBot instance with valid configuration
2. Run the bot and verify console output shows periodic "Ping!" messages
3. Confirm state and state_message are logged during heartbeat
4. Verify the bot properly terminates heartbeat when done flag is set to true
This change enables monitoring of the bot's status during meeting sessions, which is …
=> feat:heartbeat-test-meets

src/backend/pnpm-workspace.yaml, src/bots/meets/.npmrc, src/bots/meets/pnpm-workspace.yaml, src/bots/zoom/.npmrc, src/bots/zoom/pnpm-workspace.yaml, src/frontend/.npmrc, src/frontend/pnpm-workspace.yaml, src/landing-page/.npmrc, src/landing-page/pnpm-workspace.yaml
Configured PNPM workspaces for each project directory to enable isolated package management.
- Added `.npmrc` configurations to frontend, landing-page, and bot directories
- Created `pnpm-workspace.yaml` files for each project directory
- Updated backend `.npmrc` with workspace-specific settings
- Each workspace is configured to manage dependencies independently
1. Run `pnpm install` in each project directory
2. Verify that dependencies are installed locally in each workspace
3. Confirm that package installations don't affect other workspaces
4. Check that each workspace maintains its own node_modules
This change isolates package management for each project component, preventing dependency conflicts and allowing for more efficient development workflows. It enables teams to work …
=> feat: add pnpm workspace configuration

src/bots/meet/src/bot.ts
This is a redo of a previously closed PR, using the new bots format
Improved Google Meet bot recording capabilities and added automatic camera/microphone controls
- Implemented browser-based recording using MediaRecorder API instead of video capture
- Added automatic camera and microphone muting when joining meetings
- Enhanced meeting kick detection with multiple verification methods
- Added system audio recording while filtering out microphone input
- Implemented chunk-based recording with buffer management
1. Join a Google Meet as a bot
2. Verify camera and microphone are automatically disabled
3. Start a recording and confirm system audio is captured
4. Test various meeting exit scenarios:
- Being kicked from meeting
- Being the last person in meeting
- Normal meeting exit
5. Verify …
=> feat-new-recording-for-google

src/backend/src/routers/apiKeys.ts
=> feat: add get api key count

src/bots/meet/src/bot.ts
Improved Google Meet bot's automatic leaving behavior by implementing participant tracking and configurable timeout settings.
- Added participant counting functionality to accurately track meeting attendance
- Implemented a configurable timeout for waiting room and post-everyone-left scenarios
- Enhanced screen recording to only capture the window content
- Improved meeting exit detection logic with better error handling
- Added logging for participant count changes and timeout status
1. Join a Google Meet with the bot
2. Have other participants join and leave the meeting
3. Verify the bot logs participant count changes correctly
4. Leave the meeting until only the bot remains
5. Confirm the bot exits after the configured timeout period
6. Test the bot's behavior when kicked or removed …
=> fix-proper-leave-on-timeout

src/backend/src/routers/bots.ts, src/bots/src/index.ts, src/bots/zoom/Dockerfile, src/bots/zoom/src/bot.ts
Added logging for bot heartbeat events
Added a console.log statement to track when heartbeat signals are received from bots, including the bot's ID
To improve debugging capabilities and monitoring of bot activity by making it easier to track when bots are actively sending heartbeat signals to the server
=> feat: add bot heartbeat logging

src/backend/request_testing.http, src/backend/src/db/schema.ts, src/backend/src/routers/apiKeys.ts, src/backend/src/routers/events.ts
Removed `userId` from API requests and improved authentication by using the authenticated user's ID from the context.
Completes MEE-172
=> refactor: remove userId from request payloads and enhance auth

src/backend/src/services/botDeployment.ts
I believe that this is the last thing I need to do to
closes MEE-150
=> feat: add switcher to support all platforms on aws

src/bots/meet/src/bot.ts
Enhanced the Google Meet bot with improved documentation, code organization, and removed unused functionality.
Completes MEE-194 
Completes MEE-181 (legacy, but commented)
- Added comprehensive JSDoc comments to explain function purposes and parameters
- Improved code organization with better section headers and explanations
- Removed the unused `sendHeartbeat()` method from the Bot interface and implementations
- Enhanced recording functionality with better error handling and logging
- Added detailed comments about browser anti-detection techniques
- Cleaned up redundant console logs and improved existing logging
- Added UI verification date comments to help with future maintenance
- Improved error handling in the recording functionality
- Consolidated kick detection logic with better …
=> doc: Document Meet Bot

src/bots/meet/Dockerfile, src/bots/meet/package.json, src/bots/meet/pnpm-lock.yaml
=> refactor: update meet dockerfile to work post bots folder refactor

src/bots/teams/Dockerfile, src/bots/teams/src/bot.ts
=> fix: fix teams docker container after refactor

src/frontend/src/app/components/Dashboard.tsx
It looked squished on some browsers, complete MEE-200
=> fix: adjust height of top 3 dashboard cards

src/example-app/src/app/api/callback/route.ts, src/example-app/src/app/api/send-bot/route.ts, src/example-app/src/app/components/MeetingBotCreator.tsx, src/example-app/src/app/components/RecordingPlayer.tsx
Replaced polling with Server-Sent Events (SSE) for real-time recording link updates and improved error handling in the callback API.
- Added SSE support in the `/api/callback` endpoint to maintain persistent connections with clients
- Created a client storage array to track connected clients for broadcasting updates
- Refactored the `RecordingPlayer` component to use EventSource instead of React Query polling
- Improved error handling and validation in the bot API interactions
- Fixed environment variable reference in the send-bot route
- Cleaned up console logs and improved code organization
1. Start the application and navigate to the recording player
2. Create a new meeting bot
3. When the recording becomes available, verify that the player updates in real-time without refreshing
4. …
=> feat:example-app-better-polling

README.md
=> docs: update README with comprehensive project information

src/landing-page/src/app/page.tsx
One of the largest PRs in history.
=> chore: landing page 2024 to 2025 update

src/bots/zoom/src/bot.ts
=> feat(zoom): added comments and reorganized some things

src/server/src/app/__tests__/page.test.tsx, src/server/src/app/page.tsx, src/server/src/components/custom/ErrorAlert.tsx, src/server/src/components/ui/skeleton.tsx
Converted the Home page from a server component to a client component with proper loading states and error handling.
- Converted the Home page from a server component to a client component by adding the "use client" directive
- Replaced server-side auth with client-side `useSession` hook from next-auth/react
- Replaced server-side API prefetching with client-side `useQuery` from tRPC
- Added loading states with skeleton components while data is being fetched
- Added error handling with an ErrorAlert component
- Updated tests to match the new client-side implementation, including tests for loading states and error handling
- Added additional test cases to cover all possible states of the component
1. Verify the Home page loads correctly for unauthenticated users
2. Sign in and verify the …
=> test and fix: test and correct dashboard behaviour

.github/workflows/test.yml, src/server/.gitignore, src/server/jest.config.cjs, src/server/package.json, src/server/playwright.config.ts, src/server/pnpm-lock.yaml, src/server/src/app/docs/page.tsx, src/server/src/app/docs/react-swagger.tsx, src/server/tests-e2e/auth.setup.ts, src/server/tests-e2e/authenticated-features.spec.ts, src/server/tests-e2e/integration.spec.ts, src/server/tests-e2e/public-pages.spec.ts
=> feat: add e2e testing

src/bots/README.md, src/bots/envBotDataExample.ts
Improved the bot documentation with clearer structure, better explanations, and enhanced environment setup instructions.
- Restructured the README.md with a comprehensive introduction explaining bot functionality
- Added detailed file structure documentation with improved formatting
- Enhanced environment setup instructions with clearer steps
- Improved platform-specific meeting info documentation
- Added better explanations for local testing, building, and running
- Updated the `envBotDataExample.ts` script to handle URL decoding and properly update existing BOT_DATA entries
The previous documentation lacked clear structure and comprehensive explanations, making it difficult for developers to understand and use the bot system. These improvements provide better guidance for setting up the …
=> doc:updated-bot-readme-and-env-loader-update

src/example-app/README.md, src/example-app/pnpm-lock.yaml, src/example-app/src/app/api/callback/route.ts, src/example-app/src/app/api/transcribe/route.ts, src/example-app/src/app/components/AppSection.tsx, src/example-app/src/app/components/MeetingBotCreator.tsx, src/server/pnpm-lock.yaml
Fix type errors preventing build
=> fix: example app build fixes

infracost.yml, src/terraform/alb.tf, src/terraform/ec2.tf, src/terraform/ecs.tf
this should help reduce constant costs
=> feat: move server over to ec2 instance

src/bots/meet/Dockerfile, src/bots/meet/package.json
Like #320, fix the versions to a specific one until we can choose a way to keep this up to date for both playwright and puppeteer.
=> fix(meet): match playwright versions

src/bots/meet/src/bot.ts
The recording path was having permission denied.
=> fix(meet): change recording path

src/bots/meet/src/bot.ts
In the new UI the people button doesn't have the aria label anymore. 
It does have an icon element with 'people' text content and that seems to be the most stable element that is nested within the new People button.
Leaving out fallback to the old People button to account for potential gradual rollout of the new UI.
=> fix(meets): find people button in new UI
