meetingbot/meetingbot

- .gitignore
- src/backend/.gitignore
- src/backend/__init__.py
- src/backend/main.py
- src/backend/models.py
- src/backend/routes/__init__.py
- src/backend/routes/audio.py
- src/backend/routes/bots.py
- src/backend/routes/meetings.py
Restructured backend code, added new routes, and updated .gitignore. Part of MEE-43.
- Implemented new endpoints for submitting meeting links, getting meeting status, filtering meetings, generating audio download links, setting up bots, and handling bot heartbeats
- Created new route files for meetings, audio, and bots
- Refactored main.py to use separate route files
- Added models.py for future database models
- Updated .gitignore to include .pytest_cache, venv, and \_\_pycache__
- Removed src/.gitkeep and src/backend/.gitignore
- Added \_\_init__.py files for relative import fixes
The next PR in the stack adds testing capabilities.
This restructuring improves code organization and modularity, making it easier to maintain and expand the backend. The new endpoints will provide essential …
> feat: restructure backend and add API routes

- src/bots/teams/Dockerfile
- src/bots/teams/package.json
Added Docker support for Teams bot and included start script command
- Created a Dockerfile for containerizing the Teams bot using Node.js LTS Alpine image
- Added `start` script command in package.json using tsx to run the application
- Configured Docker container to expose port 3000
1. Build the Docker image:
```bash
docker build -t teams-bot .
```
2. Run the container:
```bash
docker run -p 3000:3000 teams-bot
```
3. Verify the application starts successfully
To enable containerized deployment of the Teams bot, making it easier to deploy and run in various environments while ensuring consistency across different platforms.
> feat: add docker file for teams

- src/bots/zoom/Dockerfile
- src/bots/zoom/package.json
- src/bots/zoom/src/index.ts
Added initial Zoom bot implementation with Docker configuration for automated meeting joining and recording.
- Created a Dockerfile for containerized deployment using Node.js LTS Alpine
- Implemented a Zoom bot using Puppeteer for automated meeting interactions
- Added functionality to parse and join Zoom meetings via web client
- Included audio/video stream recording capabilities
- Set up package configuration with necessary dependencies
1. Build and run the Docker container
2. Update the Zoom meeting URL in `src/index.ts`
3. Run the bot using `pnpm start`
4. Verify that the bot:
- Joins the specified Zoom meeting
- Enters with the name "Meeting Bot"
- Connects to audio/video
- Records the meeting stream to `test.webm`
To provide an automated solution for joining and recording Zoom …
> feat: bot joins zoom meeting

- .gitignore
- src/bots/zoom/src/index.ts
Added automatic meeting end detection and improved code documentation for the Zoom recording bot.
- Added a function to continuously check for meeting end status
- Implemented automatic recording stop when meeting ends
- Added descriptive comments throughout the code
- Changed recording format from .webm to .mp4
- Updated .gitignore to exclude .mp4 files
1. Start the bot with a valid Zoom meeting URL
2. Let the bot join the meeting and start recording
3. End the meeting from the host side
4. Verify that the bot automatically detects the meeting end
5. Confirm that the recording stops and is saved properly
6. Check that the browser closes automatically
Previously, the recording would stop after a fixed timeout of 10 seconds, regardless of the meeting status. This change makes the bot more …
> feat: add mp4 recording and meeting end detection

- src/bots/zoom/src/index.ts
Enhanced Zoom meeting recording reliability by improving timing and validation checks
- Increased wait times between actions from 500ms to 700ms for better stability
- Added validation to ensure the "Leave" button is properly labeled before starting recording
- Added logging to confirm when the meeting is ready for recording
- Clarified comment about meeting end check frequency
1. Run the bot with the updated Zoom meeting URL
2. Verify the bot successfully:
- Joins the meeting
- Waits for proper button labeling
- Starts recording
- Monitors for meeting end
3. Confirm the recording starts only after the leave button is properly detected
To improve the reliability of the recording process by ensuring all UI elements are properly loaded and labeled before taking actions. This prevents …
> feat: start recording when fully joined

- src/bots/meets/package.json
- src/bots/meets/pnpm-lock.yaml
- src/bots/meets/src/index.ts
Added video recording capabilities to Google Meet bot using playwright-video
Completes MEE-66
- Added `@ffmpeg-installer/ffmpeg` and `playwright-video` dependencies
- Integrated video recording functionality into the Meet bot
- Configured recording options with 25 fps
- Added automatic recording stop when leaving the meeting
- Updated the test Meet URL
1. Run the bot with the updated dependencies
2. Join a Google Meet call
3. Verify that a video file (test.mp4) is created
4. Confirm recording stops automatically when the last person leaves
5. Check the recorded video quality and fps settings
To capture and preserve Google Meet sessions for documentation, analysis, or record-keeping purposes. The video recording feature allows for automated capture of meeting content without manual …
> bot-meet-record-video

- src/bots/teams/src/index.ts
Added support for both Windows and Mac in Teams meeting leave button detection.
Updated the leave button selector to handle both Windows (`Ctrl+Shift+H`) and Mac (`⌘+Shift+H`) keyboard shortcuts. Extracted the selector into a constant to maintain consistency across multiple uses and simplified the page wait function.
The selector was also being a  bit finicky so I changed the logic slightly to follow this example from documentation:
```
@example
Arguments can be passed from Node.js to pageFunction:
const selector = '.foo';
await page.waitForFunction(
selector => !!document.querySelector(selector),
{},
selector
);
```
1. Join a Teams meeting using the bot
2. Verify the bot successfully detects when it has joined the meeting
3. Test on both Windows and Mac environments to ensure the leave …
> fix: teams bot for mac

- src/bots/zoom/Dockerfile
- src/bots/zoom/package.json
- src/bots/zoom/pnpm-lock.yaml
- src/bots/zoom/src/index.ts
Updated Zoom bot Docker configuration to use the official Puppeteer image and upgraded dependencies. Using Rosetta emulation fixes issues.
- Switched base Docker image from `node:22-alpine` to `ghcr.io/puppeteer/puppeteer:latest`
- Simplified Docker configuration by removing manual Chrome dependencies
- Updated Puppeteer from v23.3.0 to v23.9.0
- Updated puppeteer-stream from v3.0.15 to v3.0.19
- Streamlined browser launch configuration by removing unnecessary arguments
- Updated test Zoom meeting URL
- Changed Docker Desktop locally to include Rosetta emulation
1. Build the Docker container using the updated Dockerfile
2. Run the container and verify the bot can successfully connect to Zoom meetings
3. Confirm screen recording functionality works as expected
The official Puppeteer Docker …
> refactor: use puppeteer base image and clean up docker config

- src/backend/src/db/schema.ts
- src/backend/src/routers/bots.ts
- src/backend/src/routers/users.ts
Enhanced bot management system with deployment tracking and expanded user management capabilities.
Deployment tracking is for #82.
- Added deployment status tracking (`PENDING`, `DEPLOYING`, `DEPLOYED`, `FAILED`) for bots
- Reintroduced meeting info fields: `organizerId`, `tenantId`, `messageId`, `threadId`
- Renamed `meetingLink` to `meetingUrl` and `passcode` to `meetingPassword`
- Added recording management with a new `getRecording` endpoint
- Implemented new user management endpoints: `updateUser` and `deleteUser`
- Added `lastHeartbeat` and `deploymentError` tracking for bots, heartbeat is for #83 
- Simplified bot response handling by removing unnecessary meetingInfo fallbacks
> feat: enhance bot schema and add user endpoints

- src/backend/src/db/schema.ts
- src/backend/src/routers/events.ts
- src/backend/src/routers/index.ts
Added event tracking system with standardized event types and CRUD operations
- Defined structured event types with descriptions (PARTICIPANT_JOIN, PARTICIPANT_LEAVE, etc.)
- Created Zod schemas for event validation and type safety
- Added event data structures for different event types (participant data, log data, status data)
- Implemented complete CRUD API endpoints for event management:
- GET /events
- GET /events/bot/{botId}
- GET /events/{id}
- POST /events
- PATCH /events/{id}
- DELETE /events/{id}
> feat: add events router and schema

- src/backend/src/db/schema.ts
Added Zod schema definitions for bot configuration and automatic leave settings, to be consistent with #77 
- Created new schema definitions for bot configuration validation:
- `silenceDetectionSchema`: Defines timeout and activation parameters
- `botDetectionSchema`: Specifies detection settings using participant events and names
- `automaticLeaveSchema`: Combines silence detection, bot detection, and various timeout settings
- `botConfigSchema`: Extends existing bot schema with display name, image, callback URL, heartbeat, and automatic leave settings
> feat: add bot configuration schema

- src/backend/src/db/schema.ts
- src/backend/src/routers/bots.ts
Added a new `deployBot` endpoint to manage bot deployment status and configuration.
We will still need to figure out how to actually deploy the bots, but this is a placeholder for now.
- Created a new `deployBotInputSchema` to validate deployment requests
- Added a `deployBot` mutation endpoint that:
- Updates bot status to "DEPLOYING" when started
- Handles success by setting status to "DEPLOYED"
- Handles failures by setting status to "FAILED" with error message
- Returns the updated bot object
To provide a structured way to manage bot deployments and track their status, enabling better monitoring and error handling of the deployment process
> feat: add bot deployment endpoint

- src/backend/src/db/schema.ts
- src/backend/src/routers/bots.ts
Added a new heartbeat endpoint for bots to report their status and events
- Created a new `heartbeatSchema` to validate bot heartbeat requests
- Added a new `heartbeat` mutation endpoint to the bots router
- The endpoint updates the bot's `lastHeartbeat` timestamp
- Allows bots to submit events in bulk during heartbeat
Completes MEE-140
> feat: add bot heartbeat endpoint

- src/bots/zoom/src/index.ts
Improved the Zoom bot's meeting join sequence and added media stream handling capabilities.
- Added fake device handling for media streams
- Reordered the meeting join sequence to mute audio and stop video before entering name
- Added proper logging for join meeting confirmation
- Implemented additional wait times for UI elements to load properly
1. Run the bot with the provided Zoom URL
2. Verify that the bot:
- Mutes audio immediately
- Stops video feed
- Enters name as "Meeting Bot"
- Successfully joins the meeting
3. Confirm all console logs appear in the correct sequence
To create a more reliable and predictable meeting join sequence while ensuring the bot enters meetings with audio and video disabled by default. This prevents any potential disruptions to ongoing meetings and …
> fix: update zoom meeting joining behaviour

- src/backend/.dockerignore
- src/backend/.env.example
- src/backend/Dockerfile
- src/backend/docker-compose.yml
- src/backend/package.json
- src/backend/src/db/index.ts
- src/backend/src/server/index.ts
Added Docker support to the backend service and adjusted database connectivity settings.
- Created Dockerfile and docker-compose.yml for containerization
- Added .dockerignore to exclude unnecessary files
- Updated database connection configuration for SSL handling
- Modified default port to 3001
- Updated example environment variables
- Fixed eslint version compatibility issue
1. Copy `.env.example` to `.env` and update with your database credentials
2. Run development environment:
```bash
docker-compose up backend-dev
```
3. Run production environment:
```bash
docker-compose up backend
```
4. Verify the API is accessible at `http://localhost:3001`
---
Completes MEE-129
> feat: add Docker support for backend

- src/bots/meets/package.json
- src/bots/meets/pnpm-lock.yaml
- src/bots/meets/src/index.ts
- src/bots/meets/src/trpc.ts
Added tRPC client integration to Meets bot for type-safety with the backend.
For now I added an example heartbeat request as a demonstration, but commented it out.
Completes MEE-132
> feat: integrate tRPC client in Meets bot

- .github/workflows/docker.yml
Added Docker build workflows for Google Meet and Zoom bots
- Added new GitHub Actions workflow jobs for building and pushing Docker images for Google Meet and Zoom bots
- Each bot has its own dedicated build job with appropriate registry paths
- Configured permissions and authentication for container registry access
1. Push a change to the repository
2. Verify that new workflow jobs for Meet and Zoom execute successfully
3. Check the container registry for new images under:
- `meetingbot/bots/meet`
- `meetingbot/bots/zoom`
To enable automated Docker image builds for Google Meet and Zoom bot components, ensuring consistent deployment and versioning alongside the existing Teams bot workflow.
> feat:docker_github_action_meets

- src/frontend/.env.example
- src/frontend/src/app/page.tsx
- src/frontend/src/env.js
- src/frontend/src/trpc/trpc-react.tsx
- src/frontend/src/trpc/trpc-vanilla.tsx
Updated environment configuration and tRPC client setup to properly connect with the backend service.
- Simplified `.env.example` by removing unused auth variables and adding `BACKEND_URL`
- Updated the homepage to fetch all bots instead of a single bot with ID 2
- Standardized the backend URL to use port 3001 across tRPC clients
- Removed redundant URL generation logic in favor of direct environment variable usage
- Streamlined environment variable validation in `env.js`
1. Copy `.env.example` to `.env`
2. Set your `DATABASE_URL` and verify `BACKEND_URL` points to your backend service
3. Start the frontend application
4. Verify the homepage loads and displays the first bot in the list
5. Confirm tRPC requests are successfully reaching the backend at port 3001
> fix: tRPC config fix

- src/bots/meets/src/bot.ts
Added fake media stream handling and fixed async recording cleanup in the Meeting Bot
- Added Chrome flags to handle fake media streams for audio and video
- Added null device paths for fake audio and video capture
- Made `stopRecording()` call in `leaveMeeting()` await properly
1. Start a meeting with the bot
2. Verify the bot joins without media permission prompts
3. Leave the meeting and confirm recording stops cleanly
4. Check that no media permission dialogs appear during the session
The bot should not show any video or audio.
> fix: meets recording fix + disable bot video & audio

- src/bots/meets/Dockerfile
- src/bots/teams/Dockerfile
- src/bots/zoom/Dockerfile
Removed `.env` and `config.json` file copying from Docker configurations across meeting platform bots.
- Removed `COPY .env ./` and `COPY config.json ./` from all the bots in the Dockerfile
1. Build Docker images for each bot (meets, teams, zoom)
2. Verify that the containers start successfully without the .env and config files
3. Confirm that environment variables and configuration can be properly injected at runtime
Environment variables and configuration should be injected at runtime rather than baked into the Docker image for better security practices and flexibility across different deployment environments. This change prevents sensitive information from being included in the Docker image layers.
> refactor: remove config and env files from Dockerfiles

- src/bots/meets/src/bot.ts
- src/bots/meets/src/index.ts
Added detection for when a bot gets kicked from a Google Meet and improved meeting exit handling.
- Added detection for when a bot gets kicked from a meeting using a "Return to home screen" button selector
- Implemented a continuous loop to check meeting end conditions every second
- Added proper leave button detection before attempting to click it
- Enhanced logging for better debugging
- Added a 15-second delay before proceeding with recording operations
- Improved error handling around the meeting exit process
1. Join a Google Meet with the bot
2. Have a host kick the bot from the meeting
3. Verify the bot detects being kicked and exits gracefully
4. Check that recordings are properly saved
5. Verify the bot properly exits when it's the last person in the meeting
Previously, the bot …
> feat:meet_bot_can_be_kicked

- src/backend/request_testing.http
- src/backend/src/db/migrations/0001_new_snowbird.sql
- src/backend/src/db/migrations/0002_fast_phil_sheldon.sql
- src/backend/src/db/migrations/meta/0001_snapshot.json
- src/backend/src/db/migrations/meta/0002_snapshot.json
- src/backend/src/db/migrations/meta/_journal.json
- src/backend/src/db/schema.ts
- src/backend/src/routers/apiKeys.ts
- src/backend/src/routers/bots.ts
- src/backend/src/routers/events.ts
- src/backend/src/routers/index.ts
- src/backend/src/routers/users.ts
- src/backend/src/server/trpc.ts
Added API key authentication and request logging system for secure API access.
Btw there's fields for request and response bodies just in case for the future (maybe we want to log just if there's an error) but for now they're just always null.
https://github.com/user-attachments/assets/909c0149-77c3-421c-bd48-ca522279941a
completes MEE-155, completes MEE-156, completes MEE-101, completes MEE-157
- Created new database tables for API keys and request logs
- Added API key middleware for authentication
- Converted public procedures to protected procedures requiring API key authentication
- Implemented API key management endpoints (create, list, revoke)
- Added request logging for all API calls
- Added user ownership validation for all protected endpoints
1. Create an API key using the …
> feat: add API key authentication and request logging

- src/backend/.env.example
- src/backend/package.json
- src/backend/pnpm-lock.yaml
- src/backend/src/db/migrations/0003_whole_hellion.sql
- src/backend/src/db/migrations/meta/0003_snapshot.json
- src/backend/src/db/migrations/meta/_journal.json
- src/backend/src/db/schema.ts
- src/backend/src/routers/apiKeys.ts
- src/backend/src/routers/bots.ts
- src/backend/src/routers/events.ts
- src/backend/src/routers/users.ts
- src/backend/src/server/auth.ts
- src/backend/src/server/index.ts
- src/backend/src/server/trpc.ts
- src/bots/src/types.ts
- src/frontend/.env.example
- src/frontend/next.config.js
- src/frontend/package.json
- src/frontend/pnpm-lock.yaml
- src/frontend/src/app/page.tsx
- src/frontend/src/components/auth/SignInButton.tsx
- src/frontend/src/components/auth/SignOutButton.tsx
- src/frontend/src/env.js
- src/frontend/src/trpc/trpc-react.tsx
- src/frontend/src/trpc/trpc-vanilla.tsx
Hooked-up express auth to the backend to allow users to access backend endpoints via sessions *alongside* API key access. 
- I installed it according to [Installation Docs](https://authjs.dev/reference/express)
- I set up the env variables according to [Deployment Docs](https://authjs.dev/getting-started/deployment), [Env Variable Docs](https://authjs.dev/guides/environment-variables?framework=express)
- Took the database schema from [Drizzle Schema Docs](https://authjs.dev/getting-started/adapters/drizzle?framework=next-js#schemas)
- Set-up the front-end according to [Sign-in/Sign-out](https://authjs.dev/getting-started/session-management/login?framework=express), [Get Session](https://authjs.dev/getting-started/session-management/get-session?framework=express) which uses [Built-in …
> feat: add express auth js to allow backend access via sessions alongside api keys

- src/frontend/src/app/components/Dashboard.tsx
- src/frontend/src/app/components/ErrorAlert.tsx
- src/frontend/src/app/page.tsx
- src/frontend/src/components/ui/alert.tsx
- src/frontend/src/components/ui/skeleton.tsx
- src/frontend/src/styles/globals.css
- src/frontend/src/trpc/query-client.ts
towards MEE-169
Show the correct dashboard based on the user's session and whether or not they have yet to create an API key handling loading states, error handling, and conditional rendering appropriately.
- Updated page.tsx to conditionally render different views based on:
- Loading state
- Error state
- User session status
- API key count
- Created new `Dashboard` (for the returning user)
- Created `ErrorAlert` component (using the newly added `Alert`) to use when API fetches fail
- Added `Skeleton` component to use in loading states
- Modified query client configuration to reduce unnecessary refetching
- Added base styling rules for borders and outlines
1. Test session loading state and error states by turning off wifi or stopping the backend-server
2. Test API key count error …
> feat: seperated dashboard and welcome dashboard

- src/backend/src/routers/bots.ts
Replaced the discriminated union approach for validating bot status updates with a single object schema that uses `refine()`. The new implementation ensures that when a bot's status is set to 'DONE', a recording ID must be provided, while making the recording field optional for other statuses.
Using discriminatedUnion gave an error because it's not compatible with the automatic OpenAPI docs generator.
> fix: use zod refine instead of discriminatedUnion to be compatible with OpenAPI

- src/backend/src/services/botDeployment.ts
- Changed the directory path from `meetDir` (pointing to the meet bot) to `botsDir` (pointing to the parent bots directory)
- Updated the spawn command from `pnpm dev` to `pnpm start` to match the new directory structure
> fix: update bot deployment to use parent directory and start command

- src/bots/src/index.ts
- src/bots/src/monitoring.ts
Added recording file path to the DONE event when a bot completes execution.
- Moved the `key` variable declaration to the top level of the main function to make it accessible throughout the function scope
- Modified the `reportEvent` function to include the recording file path when reporting the DONE event
- Updated the `updateBotStatus` mutation to conditionally include the recording parameter when the event is DONE
> feat: include recording in DONE event

- src/frontend/src/app/components/SessionButton.tsx
- src/frontend/src/app/components/WelcomeDashboard.tsx
- src/frontend/src/contexts/SessionContext.tsx
- src/frontend/src/trpc/trpc-react.tsx
- src/frontend/src/trpc/trpc-vanilla.tsx
Updated API endpoint paths by removing the `/api` prefix from authentication and tRPC routes.
Modified all frontend API endpoint references to remove the `/api` prefix:
- Updated authentication endpoints from `/api/auth/signin`, `/api/auth/signout`, and `/api/auth/session` to `/auth/signin`, `/auth/signout`, and `/auth/session` respectively
- Changed tRPC endpoint from `/api/trpc` to `/trpc`
> fix: remove /api prefix from backend URLs causing critical errors

- src/backend/request_testing.http
- src/backend/src/db/schema.ts
- src/backend/src/routers/index.ts
- src/backend/src/routers/usage.ts
Added a new usage tracking feature to monitor daily bot activity.
- Created a new `usageRouter` with a `getDayUsage` endpoint to track daily bot usage
- Added a new `dailyUsageSchema` to the database schema
- Integrated the usage router into the main app router
- Added a test endpoint in the request testing file to check bot usage
1. Start the backend server
2. Use the new endpoint to check daily bot usage:
```
GET http://127.0.0.1:3001/api/usage/day
content-type: application/json
x-api-key: 0bc3598273e72800afa66146686c2c5d28cff0aa76f9381b3fd59651e63b4000
```
3. Verify that the response contains daily usage data with date, msEllapsed, and count fields
This change enables tracking and analysis of bot usage patterns over time, providing valuable insights into how frequently bots are being …
> feat: usage metric api

- src/backend/src/db/schema.ts
- src/backend/src/routers/usage.ts
- src/frontend/package.json
- src/frontend/pnpm-lock.yaml
- src/frontend/src/app/usage/components/UsageChart.tsx
- src/frontend/src/app/usage/components/UsageTooltip.tsx
- src/frontend/src/app/usage/page.tsx
Added a usage tracking dashboard with interactive charts to visualize bot usage metrics over different time periods.
Completes MEE-176
- Enhanced the `dailyUsageSchema` to include `estimatedCost` field
- Created new TRPC endpoints for usage data:
- `getAllUsage`: Retrieves usage data for all time
- `getWeekDailyUsage`: Gets daily usage for the current week
- `getMonthDailyUsage`: Gets daily usage for the current month
- Added a utility function `formatDayUsageDictToOutput` to standardize data formatting
- Implemented a new usage dashboard UI with:
- Interactive charts using Recharts library
- Filters for different time periods (week/month)
- Ability to switch between different metrics (estimated cost, bot count, active time)
- Custom tooltips showing detailed information
1. Navigate to …
> feat: frontend-usage-page

- src/frontend/.env.example
- src/frontend/src/app/components/SessionButton.tsx
- src/frontend/src/contexts/SessionContext.tsx
- src/frontend/src/trpc/trpc-react.tsx
- src/frontend/src/trpc/trpc-vanilla.tsx
When we changed the `NEXT_PUBLIC_BACKEND_URL` to `/api`, the `/docs` links broke. Here, I am changing it *back*, then adding the `/api` when necessary.
We need to update our env variables in terraform maybe? @err53 
towards MEE-175
> refactor: remove api path from NEXT_PUBLIC_BACKEND_URL to correct links to docs in front-end

- src/bots/meet/Dockerfile
- src/bots/meet/entrypoint.sh
- src/bots/meet/src/bot.ts
- src/bots/src/index.ts
Improved the Google Meet bot's recording capabilities by replacing browser-based recording with ffmpeg screen capture and enhanced the Docker environment for better audio/video support.
- Replaced the browser-based MediaRecorder implementation with ffmpeg for more reliable screen and audio capture
- Added an entrypoint script to properly initialize the virtual display, window manager, and audio system
- Updated the Docker configuration to include necessary dependencies for audio/video capture:
- Added ffmpeg, pulseaudio, fluxbox window manager, and other X11 utilities
- Configured Xvfb with better screen resolution (1920x1080)
- Fixed microphone mute button selector to match Google Meet's current UI
- Improved error handling for camera and microphone controls
- Added comprehensive JSDoc …
> fix: meet recording

- src/backend/src/routers/bots.ts
Added support for callback URL when creating bots.
Added a `callbackUrl` field to the bot creation process in the `botsRouter`. This allows users to specify a URL that will be called when certain bot events occur.
1. Create a new bot with a callback URL parameter
2. Verify the callback URL is saved correctly in the database
3. Confirm that the bot events trigger calls to the specified URL
This enhancement enables webhook functionality for bots, allowing for integration with external systems. The callback URL can be used to notify external services about bot events, enabling more complex automation workflows and integrations.
> fix: added callbackUrl

- src/backend/request_testing.http
- src/example-app/.env.example
- src/example-app/src/app/components/MeetingBotCreator.tsx
- src/terraform/.terraform.lock.hcl
Improved Zoom meeting link parsing and updated environment variable naming for callback URL.
- Enhanced the Zoom meeting link regex pattern to properly validate Zoom URLs with subdomains and password parameters
- Added a `parseZoomMeetingLink` function to extract meeting ID and password from Zoom URLs
- Updated environment variable from `CALLBACK_URL` to `NEXT_PUBLIC_CALLBACK_URL` in the example app
- Added new API testing endpoints in the request_testing.http file for bot usage and retrieval
- Implemented the Zoom meeting link parsing logic in the MeetingBotCreator component
1. Test the improved Zoom link validation with various formats:
- Links with subdomains (e.g., `https://company.zoom.us/j/123456789`)
- Links with password parameters (e.g., `https://zoom.us/j/123456789?pwd=abc123`) …
> feat: example app WORKING (proper env var)

- src/bots/envBotDataExample.ts
Completes MEE-203
Simplified the bot configuration process by automatically parsing meeting URLs instead of requiring manual entry of meeting details.
- Added URL parsing functionality to automatically extract meeting details from a meeting URL
- Simplified the `botData` configuration by removing the need to manually specify meeting parameters
- Added support for parsing different meeting platform URLs (Google Meet, Zoom, Teams)
- Implemented validation functions to check if a URL is valid for each platform
- Added helper functions to extract specific meeting parameters from URLs
- Updated the environment variable generation to use the parsed meeting information
1. Paste your meeting URL in the `url` variable at the top of the file
2. Run the script to generate the environment variables …
> refactor: bot-local-testing-url-generator

- src/bots/README.md
- src/bots/teams/Dockerfile
- src/bots/teams/package.json
- src/bots/teams/pnpm-lock.yaml
- src/bots/zoom/Dockerfile
- src/bots/zoom/package.json
- src/bots/zoom/pnpm-lock.yaml
Updated Puppeteer to v24.6.0 and fixed Docker configuration for Teams and Zoom bots to no longer used a hard-coded browser version.
- Updated Puppeteer from v23.9.0 to v24.6.0 in both Teams and Zoom bots
- Changed Docker working directory from `/app` to `/home/pptruser` for proper permissions
- Removed hardcoded `PUPPETEER_EXECUTABLE_PATH` environment variable
- Added documentation for resolving build issues by upgrading Puppeteer
1. Build and run the Docker containers for Teams and Zoom:
```bash
docker run --env-file .env teams
docker run --env-file .env zoom
```
2. If you encounter browser-related errors, follow the new instructions in the README:
```bash
cd zoom
pnpm install puppeteer@latest
```
The previous configuration had issues with browser detection and permissions. The hardcoded …
> fix:revert-uniform-docker-directory

- src/bots/.env.example
- src/bots/src/monitoring.ts
Added a HEARTBEAT_DEBUG environment variable to control heartbeat error logging -- stops flooding the terminal with 'heartbeat could not send' error if the backend is not online.
- Added a new `HEARTBEAT_DEBUG` environment variable in `.env.example` with a default value of `true`
- Modified the heartbeat error handling in `monitoring.ts` to only log errors when `HEARTBEAT_DEBUG` is not explicitly set to `false`
- Added a comment explaining the purpose of the new environment variable
1. Copy the new `HEARTBEAT_DEBUG` variable to your `.env` file
2. Set `HEARTBEAT_DEBUG=false` to suppress heartbeat error logs
3. Set `HEARTBEAT_DEBUG=true` or leave it unset to see heartbeat error logs
4. Trigger a heartbeat error (e.g., by disconnecting from the network) to verify the logging behavior
This …
> fix: turn-off-heartbeat-flooding-if-required

- src/server/src/__mocks__/next-auth/react.ts
- src/server/src/app/__tests__/page.test.tsx
Created a dedicated mock for next-auth/react to improve test maintainability.
- Added a new mock file `src/__mocks__/next-auth/react.ts` that provides a mock implementation of the `useSession` function
- Updated the page test to use the centralized mock instead of an inline mock definition
1. Run the existing tests to ensure they still pass with the new mock implementation
2. Verify that the test behavior remains consistent
This change improves the maintainability of tests by centralizing the mock implementation for next-auth/react. By moving the mock to a dedicated file, we ensure consistent mocking behavior across all tests and make it easier to update the mock in the future if the next-auth API changes.
> refactor: move auth mock outside for re-use

- src/server/eslint.config.js
- src/server/src/app/__tests__/page.test.tsx
- src/server/src/lib/testUtils.ts
Improved test utilities and ESLint configuration for better testing experience.
*Note* I tried my best to make a manual mock, i.e. under some `__mock__` folder, for `~/trpc/react`, but ran into the most obscure errors that had to do with React internals or the specific order in which Jest imports libraries. In order to make at least this helper function work, I needed to use `require` to be specific about the order in which libraries are to be imported.
- Added special ESLint rules for test files to disable certain TypeScript restrictions
- Created new test utility functions in `src/lib/testUtils.ts`:
- `createTrpcApiMock()`: Creates a mock for tRPC API
- `mockUseQuery()`: Generates properly typed mock return values for useQuery
- `mockUseMutation()`: Generates properly typed mock return …
> refactor: move trpc api mock outside for re-use

- src/server/src/app/__tests__/page.test.tsx
- src/server/src/lib/testUtils.ts
Added a `mockUseSession` utility function to simplify test setup for authenticated sessions.
- Created a new `mockUseSession` utility function in `testUtils.ts` that generates a properly typed session object for testing
- Updated the page tests to use this new utility function instead of manually creating session objects
- Exported the new utility function alongside existing test utilities
1. Run the existing tests to ensure they still pass with the new utility function
2. Try using the new `mockUseSession` utility in other test files that need to mock authentication
The previous approach required duplicating session object creation code across multiple test cases. This refactoring improves code maintainability by centralizing the session mocking logic into a reusable utility function, …
> refactor: move use session mock outside for re-use

- src/bots/meet/src/bot.ts
- src/bots/src/bot.ts
- src/bots/src/index.ts
- src/bots/src/types.ts
- src/bots/teams/src/bot.ts
- src/bots/zoom/src/bot.ts
Improved bot lifecycle management with proper resource cleanup and error handling.
- Added `endLife()` method to all bots to ensure proper cleanup of resources (browser, file streams, etc.)
- Standardized bot interface with required methods in the base `Bot` class
- Improved error handling for waiting room timeouts with a specific `WaitingRoomTimeoutError`
- Refactored `joinMeeting()` and `leaveMeeting()` methods to better separate concerns
- Updated documentation for bot methods
- Updated Zoom bot dependencies to version 23.11.1
1. Run bots against meetings with waiting rooms to verify proper timeout handling
2. Test error scenarios to ensure resources are properly cleaned up
3. Verify recording functionality works as expected across all platforms
4. Check that browsers are properly …
> refactor: bots-testable-run-functions

- .gitignore
- package.json
- src/bots/.env.example
- src/bots/__mocks__/@aws-sdk/client-s3.ts
- src/bots/__mocks__/puppeteer-stream.ts
- src/bots/__mocks__/superjson.ts
- src/bots/jest.config.js
- src/bots/meet/src/bot.ts
- src/bots/package.json
- src/bots/pnpm-lock.yaml
- src/bots/src/bot.ts
- src/bots/src/index.ts
- src/bots/src/s3.ts
- src/bots/teams/src/bot.ts
- src/bots/tests/README.md
- src/bots/tests/bot.test.ts
- src/bots/tests/bot_nav.test.ts
- src/bots/tests/s3startup.test.ts
- src/bots/tsconfig.json
- src/bots/zoom/src/bot.ts
Added Jest testing framework and improved bot code structure with better error handling and modularization. Added tests for bot creation, navigation and S3 continuity.
- Added Jest testing framework with configuration files for running tests
- Created test files for bot creation, navigation, and S3 connectivity
- Refactored bot creation into a separate function for better testability
- Extracted S3 functionality into a dedicated module
- Added better error handling in the Meet bot
- Updated Teams bot with improved screenshot functionality and cleanup
- Added environment variables for test meeting information
- Added `.gitignore` entry for screenshot files
- Set package.json type to "commonjs" for compatibility
1. Run `pnpm test` to execute the Jest test suite
2. Configure test meeting …
> feat: add bot testing framework

- src/server/src/app/usage/__tests__/UsageChart.test.tsx
- src/server/src/app/usage/components/UsageChart.tsx
- src/server/src/server/db/schema.ts
Since we do not render the values, this test remains simple, just ensuring the chart is rendered when there is data to be rendered. Maybe in the future this can be improved by mimicking hover behaviours to check the tool tip values.
> fix and test: fix and test usage chart

- src/bots/meet/src/bot.ts
- src/bots/src/bot.ts
- src/bots/teams/src/bot.ts
- src/bots/tests/bot_exit.test.ts
- src/bots/zoom/src/bot.ts
I have implemented these tests only for the meets bot as it is currently the only bot to check for it's kicked status. My next PR will be the other two bots catching up with this functionality.
Refactored meeting exit detection logic and added tests for bot exit scenarios. 
- Created a new `checkKicked()` method in the `MeetsBot` class to consolidate kick detection logic
- Added the `checkKicked()` method to the `BotInterface` and implemented stubs in `TeamsBot` and `ZoomBot`
- Added default timeout value for automatic leave when everyone has left the meeting
- Created comprehensive tests for bot exit scenarios in `bot_exit.test.ts`:
- Testing detection of empty participation
- Testing proper handling when bot is kicked
- Testing meeting exit when UI doesn't allow normal leaving
Run the …
> feat:meet-bot-exit-test-cases

- src/bots/meet/src/bot.ts
- src/bots/teams/src/bot.ts
- src/bots/tests/bot_exit.test.ts
- src/bots/zoom/src/bot.ts
Improved error handling for meeting bots to ensure proper cleanup when exiting meetings.
- Expanded test coverage for bot exit scenarios with comprehensive test cases for all bot types. Currently Zoom/Teams do not have this functionality, so these tests are skipped.
- Enhanced `MeetsBot.meetingActions()` with try/catch to handle errors during `leaveMeeting()`
- Added logging to `leaveMeeting()` for better debugging
- Implemented `startRecording()` and `stopRecording()` methods in `ZoomBot`
- Added proper cleanup in `ZoomBot.endLife()` to ensure recording is stopped
- Moved the debug screenshot location to `/tmp/`
1. Run the bot exit tests with `pnpm exec jest bot_exit.test.ts`
2. Verify that bots properly clean up resources when exiting meetings
3. Test error scenarios by forcing failures …
> fix: additional bot exit handling tests

- src/bots/__mocks__/@aws-sdk/client-s3.ts
- src/bots/__mocks__/fs.ts
- src/bots/__mocks__/puppeteer-stream.ts
- src/bots/meet/src/bot.ts
- src/bots/src/types.ts
- src/bots/teams/src/bot.ts
- src/bots/tests/bot.test.ts
- src/bots/tests/bot_exit.test.ts
- src/bots/tests/bot_nav.test.ts
- src/bots/tests/meet_recording.test.ts
- src/bots/tests/s3startup.test.ts
- src/bots/tests/teams_recording.test.ts
- src/bots/tests/zoom_recording.test.ts
- src/bots/zoom/src/bot.ts
Enhanced bot testing infrastructure with improved mocks, recording capabilities, and error handling.
- Enhanced AWS S3 client mocks to better track parameters and method calls
- Added file system mocks for testing file operations
- Refactored puppeteer-stream mocks for better logging and structure
- Improved browser handling in bots by extracting `launchBrowser()` method from `joinMeeting()`
- Added specialized recording tests for Meet, Teams, and Zoom bots
- Added custom `MeetingJoinError` class for better error handling
- Implemented `getFFmpegParams()` in MeetsBot to support testing environments
- Added S3 upload testing capabilities
- Enhanced screenshot error handling with try/catch blocks
- Improved bot navigation tests with better error handling
1. Run the test suite with `pnpm …
> feat:recording-tests

- src/bots/meet/src/bot.ts
- src/bots/teams/src/bot.ts
- src/bots/zoom/src/bot.ts
Improved screenshot functionality across Meet, Teams, and Zoom bots with consistent error handling.
I suspect that this fixes the long typecheck Check times.
- Standardized the screenshot method implementation across all three bots (Meet, Teams, Zoom)
- Added proper error handling with try/catch blocks in all screenshot methods
- Added browser initialization check before taking screenshots
- Moved null checks inside try blocks for better error handling flow
- Removed unnecessary `encoding: "binary"` parameter from Teams and Zoom bots
- Formatted code for consistency across all bots
1. Initialize each bot (Meet, Teams, Zoom)
2. Call the screenshot method on each bot
3. Verify screenshots are saved to `/tmp/{filename}`
4. Test error scenarios by calling screenshot before page/browser …
> fix:bot-screenshots

- src/bots/__mocks__/@aws-sdk/client-s3.ts
- src/bots/__mocks__/fs.ts
- src/bots/__mocks__/puppeteer-stream.ts
- src/bots/__mocks__/superjson.ts
- src/bots/tests/bot.test.ts
- src/bots/tests/bot_exit.test.ts
- src/bots/tests/bot_nav.test.ts
- src/bots/tests/meet_recording.test.ts
- src/bots/tests/s3startup.test.ts
- src/bots/tests/teams_recording.test.ts
- src/bots/tests/zoom_recording.test.ts
Added explicit Jest imports to all test files and mocks to ensure proper Jest functionality. Sometimes I didn't even get the errors, and I wasn't sure why. Tests still worked without these imports, it just makes ESLint shut up.
> fix: add missing jest imports

- src/bots/.env.example
- src/bots/src/monitoring.ts
- src/bots/test.env
Added a new test environment configuration file and improved heartbeat debugging options.
- Created a new `test.env` file for development-specific environment variables
- Removed `HEARTBEAT_DEBUG` from `.env.example` and moved it to `test.env`
- Updated the monitoring module to load the `test.env` file, which will override any overlapping variables from `.env`
- Improved documentation for the `HEARTBEAT_DEBUG` flag, clarifying its behavior when not defined
1. Create a `test.env` file in the `src/bots` directory with your desired debug settings
2. Run the bot and verify that heartbeat ping failures are logged or suppressed based on your `HEARTBEAT_DEBUG` setting
3. Confirm that the monitoring module correctly loads variables from both `.env` and `test.env` files
This change separates …
> refactor:bot-test-env

- src/bots/.env.example
- src/bots/meet/src/bot.ts
- src/bots/teams/src/bot.ts
- src/bots/test.env
- src/bots/tests/bot_exit.test.ts
- src/bots/tests/bot_nav.test.ts
- src/bots/tests/meet_recording.test.ts
- src/bots/tests/teams_recording.test.ts
- src/bots/tests/zoom_recording.test.ts
- src/bots/zoom/src/bot.ts
Improved error handling in screenshot methods and updated test environment configuration.
- Removed `HEARTBEAT_DEBUG` from `.env.example` as it's no longer needed there
- Improved error handling in screenshot methods for Meet, Teams, and Zoom bots:
- Moved page validation inside try/catch blocks
- Standardized error logging format
- Added try/catch to Zoom's screenshot method
- Added test meeting information variables to `test.env` for all three platforms
- Added environment variable validation in test files
- Fixed incorrect config references in test files (using proper mock configs for each platform)
- Skipped the Meet join test with `it.skip()`
1. Run the test suite with `pnpm test` to verify the changes
2. Ensure the screenshot functionality works correctly in each bot
3. Verify that …
> refactor: improve screenshot error handling and add test environment variables

- src/bots/meet/src/bot.ts
- src/bots/tests/bot_event.test.ts
Added tests for participant detection in video conferencing bots and made the participant count property public.
- Changed `participantCount` from a private to a public property in the `MeetsBot` class to allow access from tests
- Added new test file `bot_event.test.ts` that implements tests for participant detection
- Created comprehensive tests for Google Meet that verify the bot can detect when participants join and leave meetings
- Added skeleton test structures for Zoom and Teams bots for future implementation
1. Run the test suite with `npm test` or `jest src/bots/tests/bot_event.test.ts`
2. Verify that the Meet bot tests pass, confirming participant detection works correctly
3. Note that Zoom and Teams tests are currently skipped (marked with `it.skip`)
This change implements …
> feat:api_event_tests

- src/bots/src/index.ts
- src/bots/src/monitoring.ts
Added configurable heartbeat interval for bots
- Modified `startHeartbeat` function to accept a configurable interval parameter (defaulting to 5000ms)
- Updated the main function to read the heartbeat interval from `botData` configuration
- Added fallback to 5 seconds if the interval is not specified in the bot configuration
1. Configure a bot with a custom heartbeat interval by setting `heartbeatInterval` in the bot configuration
2. Deploy the bot and verify in logs that heartbeats are being sent at the configured interval
3. Test with a bot that doesn't specify the interval to confirm it defaults to 5 seconds
This change allows for more flexible monitoring configurations based on specific bot requirements. Some bots may need more frequent health checks, while others can operate with …
> fix:use-passed-in-heartbeat-interval

- src/server/src/server/api/services/botDeployment.ts
Fixed the path to the bots directory in the bot deployment service.
Updated the path resolution for the bots directory in `botDeployment.ts` from `"../../../bots"` to `"../../../../../bots"` to correctly locate the bots directory from the current file location.
1. Deploy a bot using the deployment service
2. Verify that the bot is correctly deployed to the proper directory
3. Confirm that no path-related errors occur during deployment
The previous path was incorrect, causing the system to look for the bots directory in the wrong location. This fix ensures that the deployment service can properly locate and interact with the bots directory, preventing deployment failures due to path resolution issues.
> fix: correct bots directory path in deployment service

- README.md
Updated project license from AGPL to LGPL.
Changed the license declaration in the README.md from GNU Affero General Public License (AGPL) to GNU Lesser General Public License (LGPL).
Verify that the README.md correctly states the project is now licensed under the GNU Lesser General Public License.
The LGPL is less restrictive than AGPL, allowing for easier integration with other software projects. This change maintains the requirement to share modifications to the source code while providing more flexibility for users of the library.
> docs: change from AGPL to LGPL in the readme

- src/bots/meet/Dockerfile
- src/bots/src/bot.ts
- src/bots/teams/Dockerfile
- src/bots/zoom/Dockerfile
Added platform validation to ensure bots run on the correct Docker image.
- Added `DOCKER_MEETING_PLATFORM` environment variable to all platform Dockerfiles (meet, teams, zoom)
- Enhanced the `createBot` function to validate that the bot's platform matches the Docker image it's running on
- Added error handling to prevent bots from running on mismatched Docker images
- Created a `validPlatformForImage` helper function to check platform compatibility
- Added special handling for "google" platform to match with "meet" image name
1. Build each platform's Docker image
2. Try to run a bot with a platform that doesn't match the Docker image (e.g., run a Teams bot on a Zoom Docker image)
3. Verify that an error is thrown with the message: "Docker image name [image] does not match platform …
> saftey:ensure-docker-and-platform-match

- src/example-app/README.md
- src/example-app/src/app/api/callback/route.ts
- src/example-app/src/app/components/MeetingBotCreator.tsx
- src/example-app/src/app/components/RecordingPlayer.tsx
Replaced SSE implementation with a manual recording fetch button to support serverless environments.
- Removed Server-Sent Events (SSE) implementation from the callback API route
- Added a "Check for Recording" button in the RecordingPlayer component to manually fetch recordings
- Updated the README to explain why we switched from automatic population to a manual button
- Fixed response parsing in MeetingBotCreator component
- Removed client tracking and notification code that was used for SSE
1. Run the example app
2. Create a meeting bot by entering a meeting link
3. After the meeting ends, click the "Check for Recording" button
4. Verify the recording appears and can be played
5. Test the transcribe and summarize functionality
The previous implementation used Server-Sent Events (SSE) …
> refactor: replace SSE with manual recording fetch for serverless compatibility

- src/bots/meet/src/bot.ts
1. When a meeting is publicly available (has "open" option) the button is different, so now bot checks for that as well
2. The "Others might see you differently popup" also can appear during the meeting after another attendee joins, so now the bots regularly checks for it
3. Changed the directory for recordings from /tmp to /rec, just for the comfort of mounting the volume locally. Hopefully has no impact on anything else?
> meet bot: support for open rooms and handling info popup

- .github/workflows/docker.yml
this should allow build checks from external contributors to work
> chore: only push container if we're deploying from the main branch

- src/bots/teams/Dockerfile
- src/bots/teams/package.json
- src/bots/teams/pnpm-lock.yaml
- src/bots/zoom/Dockerfile
- src/bots/zoom/package.json
- src/bots/zoom/pnpm-lock.yaml
The version was mismatching because the image and the puppeteer version were out of sync.
Wondering if we should just keep the latest image in the `Dockerfile` instead of the specific one we select.
Edit:
Refer to comment below.
> fix(bots): update puppeteer image and puppeteer version

- src/bots/.env.example
- src/bots/src/index.ts
- src/bots/src/monitoring.ts
Added development mode to disable heartbeat and event reporting when running bots locally.
This change makes local development easier by preventing unnecessary heartbeat and event failures.
> feat: don't send events and heartbeat in dev

- src/bots/zoom/src/bot.ts
Issue: The selector determined any legacy blue button as "Meeting Ended by Host" modal confirm. For example, "Meeting Recording" notification modal.
FIX: the selector is updated to match only the button in "Meeting Ended" modal
> [FIX] Fixed issue with Modal Ended modal

- .github/workflows/test.yml
Looks like there are some issues with the hosted database the tests are trying to run against, likely because the testing database we were using was torn down. As a temporary stopgap to prevent misleading unit tests from running, this PR disables the faulty tests.
> chore: disable server unit tests

- src/terraform/ecs.tf
this prevents migrations from failing if a .env file doesn't exist, and allows self-signed certs as used by RDS
> fix: reduce validation steps for db migration
